### ISSUE TITLE
review proposal

### ISSUE THREAD

**Issue by orbeckst** [ASU-CompMethodsPhysics-PHY494/final-2018-fourier-transforms#1]
I will review the proposal.

@ASU-CompMethodsPhysics-PHY494/fourier-transforms  Please leave a comment here once you addressed my comments.

Note that the proposal should have the names of *all team members* on it. There should be 2–4 *specific* objectives with measurable outcomes. It should be about 1 page but it can be longer if necessary.

The Proposal should guide your overall directions of the project and form the basis of your decisions of what to work on.

**Comment by orbeckst** [comment]
Please address the following points
1. include sections Problem (state what the general question is), Approach (how you are addressing the question), Objectives. You could introduce your 4 test systems in Approach and then in Objectives say: 
   1. analytically solve systems (1) - (4) to get momentum space wavefunction
   2. use numpy's DFT to ...
   3. ....
   4. Stretch Goal: ...
2. clearly number your objectives (see above – the roman numeral numbering is automatically generated, I would use standard arabic numerals in the proposal)

Minor comments
- I would also look at the numpy FFT vs DFT

Once you have addressed the points, please leave a comment here and ask to re-review.

**Comment by orbeckst** [comment]
@ASU-CompMethodsPhysics-PHY494/fourier-transforms please spend a few minutes on finalizing your proposal.

**Comment by jonahshoe** [comment]
Hey Professor,

Finishing it up now! Sorry about the wait.

On Thu, Apr 19, 2018 at 11:49 PM, Oliver Beckstein <notifications@github.com

**Comment by jonahshoe** [comment]
Updated the proposal, review when convenient!

**Comment by orbeckst** [comment]
Thanks, looking good.

I **approve the proposal**. Please get started.
